Repository volta-cli/volta, pull requests merged in 2023-12, with the labels that each got.

#1508 chore: replace atty with is-terminal
  Cargo.lock
  Cargo.toml
  crates/volta-core/Cargo.toml
  crates/volta-core/src/log.rs
  src/command/list/mod.rs
Labels: dependencies

#1600 Update to zip 0.5 to resolve bzip2 issue
  Cargo.lock
  crates/archive/Cargo.toml
Labels: dependencies

#1610 Configure `zip` not to use its `time` feature
  Cargo.lock
  crates/archive/Cargo.toml
Labels: security, dependencies

#1616 Switch to stable node-semver crate
  Cargo.lock
  Cargo.toml
  crates/volta-core/Cargo.toml
  crates/volta-core/src/hook/tool.rs
  crates/volta-core/src/inventory.rs
  crates/volta-core/src/platform/image.rs
  crates/volta-core/src/platform/mod.rs
  crates/volta-core/src/platform/tests.rs
  crates/volta-core/src/project/mod.rs
  crates/volta-core/src/project/serial.rs
  crates/volta-core/src/run/mod.rs
  crates/volta-core/src/run/npx.rs
  crates/volta-core/src/tool/node/fetch.rs
  crates/volta-core/src/tool/node/metadata.rs
  crates/volta-core/src/tool/node/mod.rs
  crates/volta-core/src/tool/node/resolve.rs
  crates/volta-core/src/tool/npm/fetch.rs
  crates/volta-core/src/tool/npm/mod.rs
  crates/volta-core/src/tool/npm/resolve.rs
  crates/volta-core/src/tool/package/metadata.rs
  crates/volta-core/src/tool/pnpm/fetch.rs
  crates/volta-core/src/tool/pnpm/mod.rs
  crates/volta-core/src/tool/pnpm/resolve.rs
  crates/volta-core/src/tool/registry.rs
  crates/volta-core/src/tool/yarn/fetch.rs
  crates/volta-core/src/tool/yarn/metadata.rs
  crates/volta-core/src/tool/yarn/mod.rs
  crates/volta-core/src/tool/yarn/resolve.rs
  crates/volta-core/src/toolchain/mod.rs
  crates/volta-core/src/toolchain/serial.rs
  crates/volta-core/src/version/mod.rs
  crates/volta-core/src/version/serial.rs
  crates/volta-migrate/Cargo.toml
  crates/volta-migrate/src/v2.rs
  crates/volta-migrate/src/v3/config.rs
  src/command/list/human.rs
  src/command/list/mod.rs
  src/command/list/plain.rs
  src/command/list/toolchain.rs
  tests/acceptance/corrupted_download.rs
  tests/acceptance/support/sandbox.rs
Labels: dependencies

#1617 Use published version of detect-indent
  Cargo.lock
  crates/volta-core/Cargo.toml
Labels: dependencies

#1417 fixed #1311
  crates/volta-core/src/tool/mod.rs
Labels: enhancement
