Repository volta-cli/volta, pull requests merged in 2024-07, with the labels that each got.

#1755 Replace Windows symlinks with `volta run` scripts
  Cargo.lock
  crates/volta-core/Cargo.toml
  crates/volta-core/src/fs.rs
  crates/volta-core/src/layout/mod.rs
  crates/volta-core/src/shim.rs
  crates/volta-layout/src/lib.rs
  crates/volta-layout/src/v4.rs
  crates/volta-migrate/src/lib.rs
  crates/volta-migrate/src/v4.rs
  tests/acceptance/migrations.rs
Labels: enhancement

#1786 Better error messages for unsupported `uninstall` arguments
  crates/volta-core/src/error/kind.rs
  src/command/uninstall.rs
  tests/acceptance/direct_uninstall.rs
  tests/acceptance/volta_uninstall.rs
Labels: bug, delight, error messages

#1292 Check volta shims for reachability during tool install
  Cargo.lock
  crates/volta-core/Cargo.toml
  crates/volta-core/src/tool/mod.rs
  crates/volta-core/src/tool/node/mod.rs
  crates/volta-core/src/tool/npm/mod.rs
  crates/volta-core/src/tool/package/configure.rs
  crates/volta-core/src/tool/yarn/mod.rs
  tests/acceptance/support/sandbox.rs
  tests/acceptance/volta_install.rs
Labels: bug

#1794 Simplify the Dependabot config
  .github/dependabot.yml
Labels: infrastructure

#1795 build(deps): update lockfile for latest `which`
  Cargo.lock
Labels: dependencies

#1815 infra: enable tracing-level logging
  Cargo.lock
  crates/archive/Cargo.toml
  crates/volta-core/src/log.rs
  src/cli.rs
  src/main.rs
Labels: enhancement
