Repository volta-cli/volta, pull requests merged in 2024-01, with the labels that each got.

#1611 Update Rust version to 1.75
  .github/workflows/api-docs.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  ci/build-linux.sh
  ci/docker/Dockerfile
  rust-toolchain.toml
Labels: infrastructure, breaking-change, dependencies

#1649 chore: update to clap 4
  Cargo.lock
  Cargo.toml
  src/cli.rs
  src/command/completions.rs
  src/command/fetch.rs
  src/command/install.rs
  src/command/list/mod.rs
  src/command/pin.rs
  src/command/run.rs
  src/command/setup.rs
  src/command/uninstall.rs
  src/command/use.rs
  src/command/which.rs
  src/main.rs
Labels: dependencies

#1650 Remove code signing and update installer icon
  .github/workflows/release.yml
  wix/volta.ico
Labels: infrastructure, windows

#1651 Add colors back to help output
  Cargo.lock
  Cargo.toml
  src/cli.rs
Labels: enhancement, delight

#1635 Build universal binary for Mac
  .github/workflows/release.yml
  ci/build-macos-arm.sh
  ci/build-macos-x86_64.sh
  ci/build-macos.sh
  dev/unix/volta-install.sh
Labels: enhancement

#1619 Describe Volta's SemVer commitments (COMPATIBILITY.md)
  COMPATIBILITY.md
Labels: docs

#1659 chore: replace hyperx with headers
  Cargo.lock
  Cargo.toml
  crates/archive/Cargo.toml
  crates/archive/src/tarball.rs
  crates/volta-core/Cargo.toml
  crates/volta-core/src/tool/node/resolve.rs
  tests/acceptance/support/sandbox.rs
Labels: dependencies
